events {
    worker_connections 1024;
}

http {
    upstream backend_pool {
        server 10.7.26.25:3001;  # Mac 3 — Backend A
        server 10.7.11.96:3002;  # Mac 4 — Backend B
    }

    server {
        listen 443 ssl;
        server_name app.abd.test api.abd.test;

        ssl_certificate     /Users/ritik./cn-project/certs/app.abd.test+1.pem;
        ssl_certificate_key /Users/ritik./cn-project/certs/app.abd.test+1-key.pem;

        location / {
            proxy_pass http://backend_pool;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
